import React, { useState, useEffect, useRef } from 'react';
import { Scrollama, Step } from 'react-scrollama';
import HeatMap from './heatmap';
import RadarChart from './radar';
import LineChart from './linechart';
import ScatterPlot from './scatterplot';
import BarChart from './barchart'; 

// This hook sets the dimensions of the current div
const useResizeObserver = (ref) => {
  const [dimensions, setDimensions] = useState(null);
  useEffect(() => {
    const observeTarget = ref.current;
    if(!observeTarget) return;
    
    // Set dimensions based on the divs current size 
    const resizeObserver = new ResizeObserver((entries) => {
      entries.forEach((entry) => {
        setDimensions(entry.contentRect);
      });
    });
    
    resizeObserver.observe(observeTarget);
    return () => resizeObserver.unobserve(observeTarget);
  }, [ref]);
  return dimensions;
};

// Sub-Component, Handles one Graph Step
const GraphStep = ({ index, currentStepIndex }) => {
    const containerRef = useRef(null);
    // Get the live width/height of this specific div
    const dimensions = useResizeObserver(containerRef);

    return (
        <div className='w-screen bg-[#00121f] overflow-x-hidden no-scrollbar'>
            <div className={`flex w-screen h-[80vh] mb-20 ${index % 2 === 0 ? 'flex-row' : 'flex-row-reverse' }`}>
                
                {/* Graph Section */}
                <div className="w-2/3 flex items-center justify-center">
                    <div 
                        ref={containerRef} 
                        className={`w-11/12 h-5/6 transition-all duration-700 relative
                        ${currentStepIndex === index ? 'opacity-100 scale-100' : 'opacity-40 scale-95'}
                        `}
                    >
                        {(dimensions && index === 0) && (
                            <LineChart 
                                width={dimensions.width} 
                                height={dimensions.height} 
                            />
                        )}
                        {(dimensions && index === 1) && (
                            <BarChart 
                                width={dimensions.width} 
                                height={dimensions.height} 
                            />
                        )}
                        {(dimensions && index === 2) && (
                            <RadarChart 
                                width={dimensions.width} 
                                height={dimensions.height} 
                            />
                        )}
                        {(dimensions && index === 3) && (
                            <ScatterPlot 
                                width={dimensions.width} 
                                height={dimensions.height} 
                            />
                        )}
                        {(dimensions && index === 4) && (
                            <HeatMap 
                                width={dimensions.width} 
                                height={dimensions.height} 
                            />
                        )}
                        {/* FIXME: add options for the other graphs, ex:  */}
                        {/* {(dimensions && index === <NUM CORRESPONDING TO YOUR GRAPH>) && (
                            <YOUR GRAPH COMPONENT>
                        )} */}
                    </div>
                </div>

                {/* Text Blurb */}
                <div className="w-1/3 flex items-center justify-center relative overflow-hidden">
                    <div className={`w-10/12 transition-all duration-700 text-lg font-medium
                    ${currentStepIndex === index ? 'translate-y-0 opacity-100' : 'translate-y-20 opacity-0'}
                    `}>
                        {index === 0 && (
                            <div className='flex flex-col gap-y-2 bg-[#0a4abf] px-6 py-4 rounded-lg'>
                                <p className='text-[#fff200] text-xl text-right'>
                                    <strong>Price Depreciation Over Time</strong>
                                </p>
                                <p className='text-white text-right'>
                                    - This line chart shows the price distribution over the years for each brand of computer.
                                    The lines are generated by taking the average price of all computers that have the 
                                    same year and brand. 
                                    <br></br>
                                    - We can see that an immediate driver of cost is recency, as older computers sit near the bottom of the price bracket
                                    where as newer ones sit near the top. We can also see the importance of <strong>brand power</strong>. While most of
                                    the lines are clustered together, Apple computers are generally more expensive by a wide margin, regardless of release year. 
                                </p>
                            </div>
                        )}
                        {index === 1 && (
                            <div className='flex flex-col gap-y-2 bg-[#0a4abf] px-6 py-4 rounded-lg'>
                                <p className='text-[#fff200] text-xl text-left'>
                                    <strong>The Saturation Effect</strong>
                                </p>
                                <p className='text-white text-;eft'>
                                    - The stacked bar chart shows the number of computers each brand has over the years.
                                    Each bar represents the total amount of computers for that year, and each bar is split 
                                    into subgroups to represent the portion each brand takes up. 
                                    <br></br>
                                    - If scarcity drove prices up, we would expect to see fewer computers in recent years. 
                                    Instead, we see an explosion in volume. The number of available models peaked in 2023 and 2024 (It should be noted 2025 is not over yet, that may be in part why its amount is not near the peak of previous years.), 
                                    with brands like Lenovo and Dell flooding the market. Despite this massive saturation of options, which 
                                    usually drives prices down, the average costs (from the previous chart) kept climbing.
                                </p>
                            </div>

                        )}
                        {index === 2 && (
                            <div className='flex flex-col gap-y-2 bg-[#0a4abf] px-6 py-4 rounded-lg'>
                                <p className='text-[#fff200] text-xl text-right'>
                                    <strong>Who charges for what?</strong>
                                </p>
                                <p className='text-white text-right'>
                                    - This series of interactive radar charts compares price, GPU score, and CPU score for different brands, CPU's, Desktops, and Laptops.
                                    <br></br>
                                    - We can clearly see that <strong>specialization</strong> drives the highest price tags. 
                                    Apple commands the market lead by focusing on CPU-heavy workstations, 
                                    while Razer justifies its premium pricing through GPU-dominant gaming rigs. 
                                    Beyond brand identity, <strong>form factor</strong> plays a crucial role. 
                                    Laptops are consistently more expensive than desktops, even when performance is identical. 
                                    This suggests that consumers are not just paying for power, they are paying for the engineering required to fit that power into a portable chassis.
                                </p>
                            </div>
                        )}
                        {index === 3 && (
                            <div className='flex flex-col gap-y-2 bg-[#0a4abf] px-6 py-4 rounded-lg'>
                                <p className='text-[#fff200] text-xl text-left'>
                                    <strong>Better CPU Deals or not?</strong>
                                </p>
                                <p className='text-white text-left'>
                                    <br></br>
                                    - This visualization answers the question "Can we get a better CPU deal with better performance and cheaper price?". 
                                    <br></br> 
                                    - We applied a T-SNE algorithm on multiple CPU performance features, such as: CPU cores, CPU threads, CPU clock speed in GHz, and map high dimensional data into 2D space. 
                                    <br></br>
                                    - Although Apple and Intel dominate the market in quantities and peak performance. AMD chips tend to offer high performance with a very afforable deals. 
                                    <br></br>
                                    - Left click to see top 3 better and cheaper alternatives, Double left-clicks to exit.
                                </p>
                            </div>
                        )}
                        {index === 4 && (
                            <div className='flex flex-col gap-y-2 bg-[#0a4abf] px-6 py-4 rounded-lg'>
                                <p className='text-[#fff200] text-xl text-left'>
                                    <strong>The Premium Matrix</strong>
                                </p>
                                <p className='text-white text-left'>
                                    - The heat map shows the price distribution for each form factor of a computer given brand.
                                    Each cell represents the average price of all computers that belong to a 
                                    certain brand and form factor.
                                <br></br>
                                    - It is clear that form factors such as the Workstation, Ultrabook, 
                                    and Gaming tend to be the most expensive types of computer, while Mainstream and ATX's are the cheapest.
                                <br></br>
                                    - We can once again see the brand tax at play here, as the most expensive brands (Apple and Razer)
                                    follow the previously mentioned form factor pricing trends. 
                                </p>
                            </div>
                        )}
                    </div>
                </div>
            </div>
            {/* Barrier text */}
                <div className={`w-screen transition-all duration-700 text-lg font-medium
                    ${currentStepIndex === index ? 'translate-y-0 opacity-100' : 'translate-y-20 opacity-0'}
                    `}>
                        {index === 0 && (
                            <div className=''>
                                <p className='text-[#fff200] bg-[#0a4abf] text-xl text-center'>
                                    <strong>But time isn't the only factor. If prices are rising despite an aging market, is it because of a lack of supply? 
                                        The next chart suggests the opposite.</strong>
                                </p>
                            </div>
                        )}
                        {index === 1 && (
                            <div className='flex flex-col gap-y-2'>
                                <p className='text-[#fff200] bg-[#0a4abf] text-xl text-center'>
                                    <strong>If low supply isn't driving prices up, the cost must be coming from inside the machine. We need to look at the hardware itself.</strong>
                                </p>
                            </div>
                        )}
                        {index === 2 && (
                            <div className='flex flex-col gap-y-2'>
                                <p className='text-[#fff200] bg-[#0a4abf] text-xl text-center'>
                                    <strong>We know desktops differ from laptops, but what about the engines running them? Are all processors created equal?</strong>
                                </p>
                            </div>
                        )}
                        {index === 3 && (
                            <div className='flex flex-col gap-y-2'>
                                <p className='text-[#fff200] bg-[#0a4abf] text-xl text-center'>
                                    <strong>So we have age, supply, form factor, and silicon. But when we combine them all, who charges the most?</strong>
                                </p>
                            </div>
                        )}
                        {index === 4 && (
                            <div className='flex flex-col gap-y-2 bg-[#0a4abf] '>
                                <p className='text-[#fff200] text-xl text-center'>
                                    <br />
                                    <strong>Ultimately, the highest price tags are reserved for specialized tools from prestige brands, compounded by a 'recency tax' for the latest technology. </strong>
                                    <br />
                                    <br />
                                </p>
                                <hr className='border-[#fff200]' />
                                <p className='text-[#fff200] text-xl text-center'>
                                    <br />
                                    <strong>Website Created By:</strong>
                                    <br />
                                    Xavier Flores, Nick Nguyen, and Eddie Ormseth
                                    <br />
                                    <br />
                                </p>
                            </div>
                        )}
                    </div>

        </div>
    );
};

// Main Component 
const ScrollamaDemo = () => {
  const [currentStepIndex, setCurrentStepIndex] = useState(null);

  const onStepEnter = ({ data }) => {
    setCurrentStepIndex(data);
  };

  return (
      <div className=" bg-white overflow-x-hidden">
        <div className='relative h-screen bg-black '>
            {/* 1. Background Layer (Blurred & Positioned Behind) */}
            <div className="absolute inset-0 bg-[url('/bestbuy.png')] bg-cover bg-center blur-xs opacity-30"></div>

            {/* 2. Content Layer (Sharp & Positioned on Top) */}
            <div className="relative z-10 flex h-full justify-center items-center"> 
                <div className="flex-col flex h-20 w-screen rounded-xl space-y-10 justify-center items-center shadow-lg">
                    <h1 className='text-6xl text-[#f6eb16] font-bold'>What Affects Computer Cost?</h1>
                    <h3 className='text-2xl text-center font-light w-2/4 opacity-70'>Expore how core product characteristics such as the brand, CPU specs, and physical design influence both the item's performance and its financial value over time.
</h3>
                </div>
            </div>
        </div>
        <Scrollama offset={0.6} onStepEnter={onStepEnter}>
            {[0, 1, 2, 3, 4].map((i) => (
                <Step data={i} key={i}>
                    {/* We pass the props down to our new wrapper */}
                    <div> 
                        <GraphStep index={i} currentStepIndex={currentStepIndex} />
                    </div>
                </Step>
        ))}
      </Scrollama>
    </div>
  );
};

export default ScrollamaDemo;